name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        
      - name: Publish generated content to GitHub Pages
        uses: brachycera/fly-11ty/dist@master
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
